
version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/10.0.0.41:40001,10.0.0.41:40002,10.0.0.41:40003 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 60000:27017
